/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bali_serialport_api_SerialPort */

#ifndef _Included_io_bali_serialport_api_SerialPort
#define _Included_io_bali_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bali_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_io_bali_serialport_api_SerialPort_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     io_bali_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_bali_serialport_api_SerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     io_bali_serialport_api_SerialPort
 * Method:    setTimeoutThreshold
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_io_bali_serialport_api_SerialPort_setTimeoutThreshold
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
